### PR TITLE
Fix bug in non-updatable HtmlInputText with PrimeFaces slider

### PR DESCRIPTION
**Pull request by danilAREFY**
+ Fix bug in non-updatable HtmlInputText with PrimeFaces slider

### CODE REVIEW

**Comment by kennardconsulting** [comment]
Thanks! You're on fire :) Can you tell me more about your project?

**Comment by danilAREFY** [comment]
Welcome!
Thank to you for this great project! 
I do not really have a big project, I'm doing this for fun. 
I have a small question to you. Is there a chance to upgrade PrimeFaces to version 5.2? A large number of new features have been added. And ideally, the ability to add PrimeFaces extensions.
Sorry for my bad English.
Thank you.

**Comment by kennardconsulting** [comment]
This is not something I can do, but I would welcome your contribution. The PrimeFaces version can be found in the main, parent pom.xml - you can change it there. If you could work through the various API changes, that would be awesome!

**Comment by kennardconsulting** [comment]
These changes have now been released as Metawidget 4.2. I'd be most grateful if you could download and confirm it works for you?

**Pull request merged**
