### PR TITLE
PrimeFaces AccordionPanel

### PR DESCRIPTION
**Pull request by danilAREFY**
+ PrimeFaces AccordionPanel layout decorator
+ PrimeFaces AccordionPanel layout decorator configuration
+ PrimeFaces AccordionPanel layout decorator test

### CODE REVIEW

**Comment by kennardconsulting** [comment]
Thanks again!

Could you first check this console log? You appear to have broken an integration test: https://kennardconsulting.ci.cloudbees.com/job/Metawidget/272/console

The error is in addressbook-myfaces2-primefaces: Failed to execute goal org.codehaus.mojo:webtest-maven-plugin:1.0.0:test (jetty-integration-test) on project addressbook-myfaces2-primefaces: Executing /scratch/jenkins/workspace/Metawidget/integration-tests/java/faces/addressbook2/myfaces2-primefaces/src/test/webtest/webtest.xml failed: Wrong result for xpath >normalize-space(/html/body/div[2]/form/table/tbody/tr[3]/th)<. Expected value "Type:" but got "" -> [Help 1]

Could you please take a look?

**Comment by danilAREFY** [comment]
Yes, of course, I look.

**Comment by danilAREFY** [comment]
I think the problem inside myfaces2-primefaces\src\main\webapp\WEB-INF\metawidget.xml line 50. We should replace config="org.metawidget.layout.decorator.LayoutDecoratorConfig" to config="org.metawidget.faces.component.html.layout.primefaces.TabViewLayoutDecoratorConfig" . Can you re-run ci build?
Thanks!

**Comment by kennardconsulting** [comment]
Running now...

**Comment by kennardconsulting** [comment]
Hmmm. Same problem I'm afraid? Could you please take a look: https://kennardconsulting.ci.cloudbees.com/job/Metawidget/273/console

**Comment by danilAREFY** [comment]
Not absolutely same problem. I of course will recheck integration test as soon as I develop a similar environment configuration on my computer. (I hope tomorrow)

**Comment by danilAREFY** [comment]
I solve the problem. The problem was with the PrimeFaces Tab renderer. 
Caused by: java.lang.NullPointerException: renderer type must not be null.
at org.apache.myfaces.the 
renderkit.html.HtmlRenderKitImpl.getRenderer(HtmlRenderKitImpl.java:117). 

From myfaces source code:
```java
if (rendererType == null)
{
     throw new NullPointerException("renderer type must not be null.");
}
```
now just log: 
```java
log.warning("Unsupported component-family/renderer-type: " + componentFamily + "/" + rendererType);
```

How I can attach the new commit for this pull request? Or I should open the new?

Thank you.

**Comment by kennardconsulting** [comment]
I'm not clear what your fix is? Are you proposing to make a change to org.apache.myfaces.the
renderkit.html.HtmlRenderKitImpl? We can't really do that. You need to fix this within Metawidget.

Yes, if you make a change, you can just create a new pull request.

I'm sorry I don't have more time to help you directly at the moment. Thanks for your patience!

**Comment by danilAREFY** [comment]
I mean of course metawidget. https://github.com/metawidget/metawidget/pull/40 this request should fix this problem. Tests were completed successfully on localhost.

**Comment by kennardconsulting** [comment]
These changes have now been released as Metawidget 4.2. I'd be most grateful if you could download and confirm it works for you?

**Pull request merged**
