### PR TITLE
PrimeFaces DataTable support

### PR DESCRIPTION
**Pull request by danilAREFY**
+ PrimeFaces DataTable support
+ PrimeFaces widget builder config
+ PrimeFaces widget builder Character support
+ rewrite PrimeFacesWidgetBuilderTest and include DataTable test

### CODE REVIEW

**Comment by kennardconsulting** [comment]
Terrific! I can see you're very comfortable with the code!

**Comment by kennardconsulting** [comment]
It looks like you've copy pasted methods (createDataTableComponent, addColumnComponents, etc) from the base class (HtmlWidgetBuilder). Is there a reason that PrimeFacesWidgetBuilder can't just call its base class? Could you refactor the common code to remove duplication?

**Comment by danilAREFY** [comment]
Hello. Yes, of course I thought about it. But the main reason is because the difference in the components. (for example DataTable, Column in PrimeFaces env.) I think I can break the code into smaller sections or generalize. How do you think?

**Comment by kennardconsulting** [comment]
Yes. I'd be in favour of adding more 'hooks' into HtmlWidgetBuilder which PrimeFacesWidgetBuilder can then override. The less duplicated code, the better.

**Comment by kennardconsulting** [comment]
These changes have now been released as Metawidget 4.2. I'd be most grateful if you could download and confirm it works for you?

**Pull request merged**
