### PR TITLE
Refactor DataTable creation in HtmlWidgetBuilder & PrimeFacesWidgetBuilder

### PR DESCRIPTION
**Pull request by danilAREFY**
As has been discussed (https://github.com/metawidget/metawidget/pull/42), the code for creating the tables was changed. The tests were written before.

### CODE REVIEW

**Comment by kennardconsulting** [comment]
Much nicer! Thanks!

**Comment by kennardconsulting** [comment]
Is there a reason you have a separate PrimeFacesWidgetBuilderConfig? You can't just pass HtmlWidgetBuilderConfig to PrimeFacesWidgetBuilder?

**Comment by danilAREFY** [comment]
Yes, the main reason is that PrimeFaces DataTable does not extend HtmlDataTable. And, for example doesn't have the columnClasses attribute. Also PrimeFaces DataTable has a large number of additional settings, so the plan is to choose some of them and add them to the config.

**Comment by kennardconsulting** [comment]
Beautiful. Thanks!

**Comment by kennardconsulting** [comment]
These changes have now been released as Metawidget 4.2. I'd be most grateful if you could download and confirm it works for you?

**Pull request merged**
