### PR TITLE
+ fix PrimeFaces Tab renderer

### PR DESCRIPTION
**Pull request by danilAREFY**
+ fix PrimeFaces Tab renderer

### CODE REVIEW

**Comment by kennardconsulting** [comment]
Great! I will re-run the build.

**Comment by danilAREFY** [comment]
Aww, forgot change layout configuration in other primefaces integration test module. So build should failed now:( Now quirks-primefaces module...

**Comment by kennardconsulting** [comment]
Ha ha! No worries. Look forward to it!

**Comment by kennardconsulting** [comment]
These changes have now been released as Metawidget 4.2. I'd be most grateful if you could download and confirm it works for you?

**Pull request merged**
