### PR TITLE
Fix HtmlWidgetBuilder for character type

### PR DESCRIPTION
**Pull request by danilAREFY**

### CODE REVIEW

**Comment by kennardconsulting** [comment]
Is the new test you wrote included somewhere?

**Comment by danilAREFY** [comment]
Now, yes.
Thanks.

**Comment by kennardconsulting** [comment]
Awesome! Thanks. I take it your project is progressing well?

**Comment by danilAREFY** [comment]
Yes, everything is fine. Very nice to use this tool.

**Comment by kennardconsulting** [comment]
These changes have now been released as Metawidget 4.2. I'd be most grateful if you could download and confirm it works for you?

**Pull request merged**
