### PR TITLE
Replace HtmlInputTextarea, HtmlInputText, HtmlInputSecret for PrimeFaces components

### PR DESCRIPTION
**Pull request by danilAREFY**
+ replaced HtmlInputTextarea, HtmlInputText, HtmlInputSecret for PrimeFaces components
+ max length for PrimeFaces InputTextarea

### CODE REVIEW

**Comment by kennardconsulting** [comment]
Awesome!

Before I merge, could you please also update org.metawidget.faces.widgetbuilder.primefaces.PrimeFacesWidgetBuilderTest?

Thanks!

**Comment by danilAREFY** [comment]
Done.
Thank you.

**Comment by kennardconsulting** [comment]
Excellent. Thanks for much for your contribution!

**Comment by kennardconsulting** [comment]
These changes have now been released as Metawidget 4.2. I'd be most grateful if you could download and confirm it works for you?

**Pull request merged**
